import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
 title: "Zoogle",
 description: "Generated by create next app",
}

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <head>
    <style></style>
   </head>
   <body style={{ width: "100%", height: "100vh" }} className={inter.className}>
    {children}
   </body>
  </html>
 )
}
